### ISSUE TITLE
TypeError: process_iter() got an unexpected keyword argument 'attrs'

### ISSUE THREAD

**Issue by galou** [jnweiger/OCFFS#1]
OCFFS looks great but I have problems to run it.

```
Traceback (most recent call last):
  File "ocffs.py", line 463, in <module>
    main(sys.argv[1], sys.argv[2])
  File "ocffs.py", line 452, in main
    with OCFFS(root, mountpoint) as ocffs:
  File "ocffs.py", line 53, in __init__
    pids = self._find_owncloud_threads()
  File "ocffs.py", line 127, in _find_owncloud_threads
    for p in psutil.process_iter(attrs=['name']):
TypeError: process_iter() got an unexpected keyword argument 'attrs'
```

I have Ubuntu 16.04 and psutil version 3.4.2.

By the way, I had to change `fusepy` to `fuse` with fusepy 3.0.1 installed with pip.

**Comment by Supltz** [comment]
Traceback (most recent call last):
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 3711, in main
mainwindow = run_spyder(app, options, args)
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 3552, in run_spyder
main.setup()
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 960, in setup
self.completions.start()
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\completion\plugin.py", line 292, in start
client_info['plugin'].start()
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\completion\kite\plugin.py", line 137, in start
running = check_if_kite_running()
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 42, in check_if_kite_running
'status']):
TypeError: process_iter() got an unexpected keyword argument 'attrs'






I have a similar error.
When I uninstall Kite,it runs just fine.
